
INSERT INTO SAMPLE (INDEX, COLUMN1, COLUMN2)
  VALUES (1, 'EXAMPLE COLUMN1 DATA', 'EXAMPLE COLUMN2 DATA');
INSERT INTO SAMPLE (INDEX, COLUMN1, COLUMN2)
  VALUES (2, 'EXAMPLE COLUMN1 DATA', 'EXAMPLE COLUMN2 DATA');
  INSERT INTO SAMPLE (INDEX, COLUMN1, COLUMN2)
  VALUES (3, 'EXAMPLE COLUMN1 DATA', 'EXAMPLE COLUMN2 DATA');

COMMIT;